import type { Metadata } from "next";
import { Exo_2 } from "next/font/google";
import "./globals.css";
import SideNavbar from "@/components/SideNavbar";
import { TooltipProvider } from "@/components/ui/tooltip";



const exo2 = Exo_2({
  subsets: ["latin"],
  weight: ["400", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${exo2.className} bg-blk text-wht`}
      >
        <TooltipProvider delayDuration={1}>
          <div className="flex flex-row w-full h-screen">
            <SideNavbar />
            {children}
          </div>
        </TooltipProvider>
      </body>
    </html>
  );
}
